CREATE TABLE Role (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE Student (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    index_number VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    account_status VARCHAR(30),
    registration_date DATE,
    role_id INT NOT NULL,

    CONSTRAINT fk_student_role
        FOREIGN KEY (role_id)
        REFERENCES Role(role_id)
);

CREATE TABLE Course (
    course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    ects INT,
    hours INT,
    semester INT,
    capacity INT
);

CREATE TABLE Enrollment (
    enrollment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_date DATE,
    status VARCHAR(30),
    student_id INT NOT NULL,
    course_id INT NOT NULL,

    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id),

    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (course_id)
        REFERENCES Course(course_id),

    CONSTRAINT uq_student_course
        UNIQUE (student_id, course_id)
);

CREATE TABLE Grade (
    grade_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value DECIMAL(3,1),
    type VARCHAR(30),
    issue_date DATE,
    student_id INT NOT NULL,
    course_id INT NOT NULL,

    CONSTRAINT fk_grade_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id),

    CONSTRAINT fk_grade_course
        FOREIGN KEY (course_id)
        REFERENCES Course(course_id)
);

CREATE TABLE Schedule (
    schedule_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester INT NOT NULL,
    student_id INT NOT NULL UNIQUE,

    CONSTRAINT fk_schedule_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id)
);

CREATE TABLE ClassSession (
    class_session_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(20),
    start_time TIME,
    end_time TIME,
    room VARCHAR(30),
    form VARCHAR(30),
    schedule_id INT NOT NULL,
    course_id INT NOT NULL,

    CONSTRAINT fk_class_session_schedule
        FOREIGN KEY (schedule_id)
        REFERENCES Schedule(schedule_id),

    CONSTRAINT fk_class_session_course
        FOREIGN KEY (course_id)
        REFERENCES Course(course_id)
);

CREATE TABLE Notification (
    notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1000),
    sent_at TIMESTAMP,
    type VARCHAR(30),
    status VARCHAR(30),
    student_id INT NOT NULL,

    CONSTRAINT fk_notification_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id)
);

CREATE TABLE Payment (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(10,2),
    due_date DATE,
    status VARCHAR(30),
    payment_date DATE,
    student_id INT NOT NULL,

    CONSTRAINT fk_payment_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id)
);

CREATE TABLE Loan (
    loan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_title VARCHAR(255),
    loan_date DATE,
    return_deadline DATE,
    student_id INT NOT NULL,

    CONSTRAINT fk_loan_student
        FOREIGN KEY (student_id)
        REFERENCES Student(student_id)
);
